;;; buffer-terminator-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from buffer-terminator.el

(defvar buffer-terminator-mode nil "\
Non-nil if Buffer-Terminator mode is enabled.
See the `buffer-terminator-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `buffer-terminator-mode'.")
(custom-autoload 'buffer-terminator-mode "buffer-terminator" nil)
(autoload 'buffer-terminator-mode "buffer-terminator" "\
Toggle Buffer Terminator mode.

When enabled, this mode automatically kills buffers that have been inactive
and not visible based on a defined timeout.

This is a global minor mode.  If called interactively, toggle the
`Buffer-Terminator mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='buffer-terminator-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "buffer-terminator" '("buffer-terminator-"))

;;; End of scraped data

(provide 'buffer-terminator-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; buffer-terminator-autoloads.el ends here
