;;; org-side-tree-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-side-tree.el

(autoload 'org-side-tree "org-side-tree" "\
Create or pop to Org-Side-Tree buffer." t)
(autoload 'org-side-tree-toggle "org-side-tree" "\
Toggle side-tree window." t)
(autoload 'org-side-tree-toggle-auto-update "org-side-tree" "\
Toggle `org-side-tree-enable-auto-update' for the current buffer." t)
(autoload 'org-side-tree-toggle-folding "org-side-tree" "\
Toggle `org-side-tree-enable-folding' for the current buffer." t)
(autoload 'org-side-tree-toggle-narrow-on-jump "org-side-tree" "\
Toggle `org-side-tree-narrow-on-jump' for the current buffer." t)
(autoload 'org-side-tree-next-heading "org-side-tree" "\
Move to next heading." t)
(autoload 'org-side-tree-previous-heading "org-side-tree" "\
Move to previous heading." t)
(register-definition-prefixes "org-side-tree" '("org-side-tree"))

;;; End of scraped data

(provide 'org-side-tree-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-side-tree-autoloads.el ends here
